### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by mlotysz** [MateuszSz93/FirstTask#1]
You write far too much documentation and too much code. Try to be concise and write code which is self explanatory. You pick good names and in most cases this explain your intention to readers (us). We prefer to read implementation. We like books but after our working hours... :)

Example javadocs to be removed:
https://github.com/MateuszSz93/FirstTask/blob/master/src/main/java/pl/mszkwarkowski/api/MoviesInformantController.java#L11
https://github.com/MateuszSz93/FirstTask/blob/master/src/main/java/pl/mszkwarkowski/api/MoviesInformantController.java#L19
https://github.com/MateuszSz93/FirstTask/blob/master/src/main/java/pl/mszkwarkowski/api/MoviesInformantController.java#L27

http://softwareengineering.stackexchange.com/a/51380

**Comment by MateuszSz93** [comment]
Removed unnecessary JavaDocs.
