### ISSUE TITLE
Return empty collections + HTTP 200

### ISSUE THREAD

**Issue by mlotysz** [MateuszSz93/FirstTask#2]
It's perfectly normal to return empty collections to client. Do not throw exception in this case. Given that most of your implementation shorten to one liners.

BTW we create REST API for other *system* not for humans. You can remove REST API "for humans". Leave CRUD functionality no more, no less. :)

**Comment by MateuszSz93** [comment]
Removed throwing exceptions. Since now are returned empty collections.
