### ISSUE TITLE
Use HTTP body not HTTP headers

### ISSUE THREAD

**Issue by mlotysz** [MateuszSz93/FirstTask#3]
Example: https://github.com/MateuszSz93/FirstTask/blob/master/src/main/java/pl/mszkwarkowski/api/MoviesInformantController.java#L223

https://spring.io/understanding/REST + Use JSON and HTTP body to send movie to be updated/created...

**Comment by MateuszSz93** [comment]
Removed support for HTTP Headers. Added support for HTTP Body.
