### ISSUE TITLE
README - missuse

### ISSUE THREAD

**Issue by mlotysz** [MateuszSz93/FirstTask#4]
README depends of IntelliJ IDEA. I'm sure it was plenty of work but in long term is very hard to maintain.
We prefer to use console (common) tools: maven, curl/wget/jq for showing simple use cases - it's all text!

Example: https://github.com/nikgraf/serverless-crud/blob/master/README.md (I'm feeling lucky from google).

**Comment by MateuszSz93** [comment]
Added curl examples for showing use cases.
